### PR TITLE
Update to 2.0.0 with the proper dependency updates

### PR DESCRIPTION
**Pull request by tgjohnst**
This pull request updates to 2.0.0 and updates the following dependencies accordingly:
- replace proto dependency with R6
- replace rjson dependency with rjsonlite

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tgjohnst** [comment]
<code>@<space/>conda-forge-admin, please rerender</code>

**Comment by tgjohnst** [comment]
@conda-forge-admin, please rerender

**Comment by tgjohnst** [comment]
@conda-forge-admin, please rerender

**Comment by tgjohnst** [comment]
yay! looks like this is ready to merge :)

**Comment by dbast** [comment]
@tgjohnst Thanks. You can make your life easier by using ttps://github.com/bgruening/conda_r_skeleton_helper -> update.sh/run.sh. That is how https://github.com/conda-forge/r-argparse-feedstock/pull/6 was generated.

**Comment by tgjohnst** [comment]
@dbast thanks! I'll do that in the future. going to go ahead and close this PR since it looks like you updated already.

**Pull request closed without merging**
